ChainID = 98866
FinalityTagEnabled = true

# block_time is dynamic
LogPollInterval = "5s"
# posting to L1 every ~12 hours
NoNewFinalizedHeadsThreshold = '13h'
NoNewHeadsThreshold = '2m'

[GasEstimator]
Mode = 'FeeHistory'
EIP1559DynamicFees = false
PriceMin = "0"
BumpMin = "5 mwei"
PriceMax = '1000 gwei'

[GasEstimator.FeeHistory]
# block_time is dynamic
CacheTimeout = '4s'
