ChainID = 98866
FinalityTagEnabled = true
# block_time: 4s, adding 1 second buffer 
LogPollInterval = "5s"
# posting to L1 every ~12 hours
NoNewFinalizedHeadsThreshold = '13h'
NoNewHeadsThreshold = '2m'

[GasEstimator]
Mode = 'FeeHistory'
EIP1559DynamicFees = false
PriceMin = "0"
BumpMin = "5 mwei"
PriceMax = '1000 gwei'

[GasEstimator.FeeHistory]
# block_time was: 4s, per recommendation skip 1-2 blocks
CacheTimeout = '8s'
