ChainID = 98867
FinalityTagEnabled = true
# block_time: 6s, adding 1 second buffer 
LogPollInterval = "7s"
# posting to L1 every ~60 minutes
NoNewFinalizedHeadsThreshold = '70m'
NoNewHeadsThreshold = '2m'

[GasEstimator]
Mode = 'FeeHistory'
EIP1559DynamicFees = false
PriceMin = "0"
BumpMin = "5 mwei"
PriceMax = '1000 gwei'

[GasEstimator.FeeHistory]
# block_time was: 6s, per recommendation skip 1-2 blocks
CacheTimeout = '12s'
